### ISSUE TITLE
Move Item to Vanilla Creative Tab

### ISSUE THREAD

**Issue by ardissaps** [blay09/Fertilization#12]
It only contain 4 items, would you like to remove the tab and move the item in Vanilla tab? thank you

**Comment by BlayTheNinth** [comment]
There's different opinions on this, one time I used a Vanilla tab and others didn't like that either. 

My consensus is that an additional Creative Tab does not hurt and provides an easy overview over the items in a mod, so I have no plans to remove the tab.

**Comment by ardissaps** [comment]
To know all item of certain mod we can simply add "@" then name of the mod id on [REI](https://modrinth.com/mod/roughly-enough-items) search box :
![image](https://user-images.githubusercontent.com/82106625/176979520-103989ec-d03c-4171-bbfb-ab7caf25d510.png)
We need organized creative tab, as REI does not have tab.

Like maybe put it in together with vanilla bonemeal (or option to do so similiar with [Extended Block Shape](https://modrinth.com/mod/extshape))
![image](https://user-images.githubusercontent.com/82106625/176979563-5418c315-d207-4157-a553-63d92a7760f9.png)
